### ISSUE TITLE
Cannot put image or video.

### ISSUE THREAD

**Issue by dogenius01** [omphalos/crud-file-server#8]
Hi! 

when i put image or video, upload request get success message.
But, i cannot open image and video file.

At the front of the file, "------WebKitFormBoundaryBzJeS8LNmkg6mBDY
Content-Disposition: form-data; name=""; filename="Ronno2.PNG"
Content-Type: image/png" this kinds of text exists.

**Comment by omphalos** [comment]
@dogenius01 unfortunately I am not able to reproduce this.

Can you maybe let me know what OS and browser you are trying this on, please?

Are you able to put a repro together on github that I could take a look at?

If you copy the file (instead of uploading it) are you able to see the image/video?

Also, you describe some text at the beginning of your png file.  Maybe that is not the correct format for a png?  Wikipedia's description is [here](https://en.wikipedia.org/wiki/Portable_Network_Graphics#File_format) - I am not very familiar with PNG format, but it appears that a png should not begin with a `"` or `-` character.

**Comment by dogenius01** [comment]
Hi, @omphalos 

I just PUT with postman on window 7.
and crud-server is running on Ubuntu 16.04.2 LTS.

This is the original image. 
https://drive.google.com/file/d/1pYtwrr8C2YdeXgJeB5rHsZZb-D2PWBdY/view?usp=sharing

This is the uploaded image with put operation.
https://drive.google.com/open?id=10DLSNZCwKNYjL_slupD67ohSm_eADn3z

**Comment by dogenius01** [comment]
This is package-lock.json

{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "crud-file-server": {
      "version": "0.9.0",
      "resolved": "https://registry.npmjs.org/crud-file-server/-/crud-file-server-0.9.0.tgz",
      "integrity": "sha1-vt0hh4pREfrU7TzMM9YH4r+cgvk=",
      "requires": {
        "mime": "1.2.7",
        "optimist": "0.3.4"
      }
    },
    "mime": {
      "version": "1.2.7",
      "resolved": "https://registry.npmjs.org/mime/-/mime-1.2.7.tgz",
      "integrity": "sha1-x6E/M6cHPZkA8ohDawazoWIAhls="
    },
    "optimist": {
      "version": "0.3.4",
      "resolved": "https://registry.npmjs.org/optimist/-/optimist-0.3.4.tgz",
      "integrity": "sha1-TW0L1x/60NpLpPbYdtXusE4HSAs=",
      "requires": {
        "wordwrap": "0.0.3"
      }
    },
    "wordwrap": {
      "version": "0.0.3",
      "resolved": "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz",
      "integrity": "sha1-o9XabNXAvAAI03I0u68b7WMFkQc="
    }
  }
}

**Comment by omphalos** [comment]
@dogenius01 I was able to write then read Ronno2.png correctly using the following steps:

* Create a directory.

* Copy example.html to that directory.

* Copy Ronno2.png (your image file) into that directory.

* Host that directory using crud-file-server's `-f` option.

* Navigate to http://localhost:8080/example.html using Chrome.

* Open DevTools and execute the following code:

```js
var getReq = new XMLHttpRequest()
var image = null
getReq.open('GET', '/Ronno2.png', true)
getReq.responseType = 'blob'
getReq.onload = function() {
  image = getReq.response
  var putReq = new XMLHttpRequest()
  putReq.open('PUT', '/Ronno2-copy.png', true)
  putReq.onload = function () { console.log('done') }
  putReq.send(image)
}
getReq.send()
```

* Navigate to http://localhost:8080/Ronno2-copy.png using Chrome.

* Observe the image.

Since I was able to copy the image using the REST API, I guess the problem you're having is due to some problem with postman or how you're using postman.

Maybe there is something special you need to do on your side to get postman to properly PUT binary data?

In the example here, using `XmlHttpRequest`, I needed to request a blob then send the blob server. Using strings didn't work for me.

I hope something here might give you a hint to help you with your postman troubles.

**Comment by dogenius01** [comment]
@omphalos 
You are right. 
The problem was the way of using the postman.

I was doing put like below(form-data).
![image](https://user-images.githubusercontent.com/7548321/42739778-9b6fcf16-88d8-11e8-9928-8e33d706c8c1.png)

The problem solved by change the body as binary.
![image](https://user-images.githubusercontent.com/7548321/42739792-ded11fd0-88d8-11e8-8bb2-7010cec04fa6.png)

Thank you for the hints!
